# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74ab27f281128628a98ac16be7b92428c45bb12b79dbec9463f115f19af41b4ee543c02f4f600d4fbf1646bae8d72bf8f57de5d4f18dc6d2805713b4c711206f

test:
  secret_key_base: 150da88cb68edc3b7a8542d91789230c72cceb2c539335eddc93715bc6e5e27bcfefa8eaf650f9e2e3aefc12bf6872ff212e76d16edd383da3869aaa027c819f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
